# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# Attempt to trigger travis build 11.30.20

language: R
cache: packages

r_binary_packages:
  - devtools
  - roxygen2

after_success:
  - Rscript -e 'devtools::install();devtools::test()'
