#!/bin/bash
#SBATCH --job-name=poplar_shoot_sample.csv
#SBATCH --output=%A_%a.out
#SBATCH --error=%A_%a.err
#SBATCH --array=1-19
#SBATCH --time=01:00:00
#SBATCH --partition=broadwl
#SBATCH --ntasks=1
#SBATCH --mem=4G
Rscript MTMCSKAT_workflow.R --phenodata=poplar_shoot_sample.csv --covariates=poplar_PCs_covariates.csv --raw_file_path=/scratch2/NSF_GWAS/SKAT_SLURMS/inputs/wholeChr/MAF0.0_geno882_Chr10.traw --window_size=3000 --window_shift=1000 --output_dir=Results/ --job_id=mtmcskat_parallel_wrapper_testa1_MAF0.0_geno882_Chr10.traw --ncore=AllCores --max_accuracy=5 --sig_figs=2
Rscript MTMCSKAT_workflow.R --phenodata=poplar_shoot_sample.csv --covariates=poplar_PCs_covariates.csv --raw_file_path=/scratch2/NSF_GWAS/SKAT_SLURMS/inputs/wholeChr/MAF0.0_geno882_Chr11.traw --window_size=3000 --window_shift=1000 --output_dir=Results/ --job_id=mtmcskat_parallel_wrapper_testa1_MAF0.0_geno882_Chr11.traw --ncore=AllCores --max_accuracy=5 --sig_figs=2
Rscript MTMCSKAT_workflow.R --phenodata=poplar_shoot_sample.csv --covariates=poplar_PCs_covariates.csv --raw_file_path=/scratch2/NSF_GWAS/SKAT_SLURMS/inputs/wholeChr/MAF0.0_geno882_Chr12.traw --window_size=3000 --window_shift=1000 --output_dir=Results/ --job_id=mtmcskat_parallel_wrapper_testa1_MAF0.0_geno882_Chr12.traw --ncore=AllCores --max_accuracy=5 --sig_figs=2
Rscript MTMCSKAT_workflow.R --phenodata=poplar_shoot_sample.csv --covariates=poplar_PCs_covariates.csv --raw_file_path=/scratch2/NSF_GWAS/SKAT_SLURMS/inputs/wholeChr/MAF0.0_geno882_Chr13.traw --window_size=3000 --window_shift=1000 --output_dir=Results/ --job_id=mtmcskat_parallel_wrapper_testa1_MAF0.0_geno882_Chr13.traw --ncore=AllCores --max_accuracy=5 --sig_figs=2
Rscript MTMCSKAT_workflow.R --phenodata=poplar_shoot_sample.csv --covariates=poplar_PCs_covariates.csv --raw_file_path=/scratch2/NSF_GWAS/SKAT_SLURMS/inputs/wholeChr/MAF0.0_geno882_Chr14.traw --window_size=3000 --window_shift=1000 --output_dir=Results/ --job_id=mtmcskat_parallel_wrapper_testa1_MAF0.0_geno882_Chr14.traw --ncore=AllCores --max_accuracy=5 --sig_figs=2
Rscript MTMCSKAT_workflow.R --phenodata=poplar_shoot_sample.csv --covariates=poplar_PCs_covariates.csv --raw_file_path=/scratch2/NSF_GWAS/SKAT_SLURMS/inputs/wholeChr/MAF0.0_geno882_Chr15.traw --window_size=3000 --window_shift=1000 --output_dir=Results/ --job_id=mtmcskat_parallel_wrapper_testa1_MAF0.0_geno882_Chr15.traw --ncore=AllCores --max_accuracy=5 --sig_figs=2
Rscript MTMCSKAT_workflow.R --phenodata=poplar_shoot_sample.csv --covariates=poplar_PCs_covariates.csv --raw_file_path=/scratch2/NSF_GWAS/SKAT_SLURMS/inputs/wholeChr/MAF0.0_geno882_Chr16.traw --window_size=3000 --window_shift=1000 --output_dir=Results/ --job_id=mtmcskat_parallel_wrapper_testa1_MAF0.0_geno882_Chr16.traw --ncore=AllCores --max_accuracy=5 --sig_figs=2
Rscript MTMCSKAT_workflow.R --phenodata=poplar_shoot_sample.csv --covariates=poplar_PCs_covariates.csv --raw_file_path=/scratch2/NSF_GWAS/SKAT_SLURMS/inputs/wholeChr/MAF0.0_geno882_Chr17.traw --window_size=3000 --window_shift=1000 --output_dir=Results/ --job_id=mtmcskat_parallel_wrapper_testa1_MAF0.0_geno882_Chr17.traw --ncore=AllCores --max_accuracy=5 --sig_figs=2
Rscript MTMCSKAT_workflow.R --phenodata=poplar_shoot_sample.csv --covariates=poplar_PCs_covariates.csv --raw_file_path=/scratch2/NSF_GWAS/SKAT_SLURMS/inputs/wholeChr/MAF0.0_geno882_Chr18.traw --window_size=3000 --window_shift=1000 --output_dir=Results/ --job_id=mtmcskat_parallel_wrapper_testa1_MAF0.0_geno882_Chr18.traw --ncore=AllCores --max_accuracy=5 --sig_figs=2
Rscript MTMCSKAT_workflow.R --phenodata=poplar_shoot_sample.csv --covariates=poplar_PCs_covariates.csv --raw_file_path=/scratch2/NSF_GWAS/SKAT_SLURMS/inputs/wholeChr/MAF0.0_geno882_Chr19.traw --window_size=3000 --window_shift=1000 --output_dir=Results/ --job_id=mtmcskat_parallel_wrapper_testa1_MAF0.0_geno882_Chr19.traw --ncore=AllCores --max_accuracy=5 --sig_figs=2
Rscript MTMCSKAT_workflow.R --phenodata=poplar_shoot_sample.csv --covariates=poplar_PCs_covariates.csv --raw_file_path=/scratch2/NSF_GWAS/SKAT_SLURMS/inputs/wholeChr/MAF0.0_geno882_Chr1.traw --window_size=3000 --window_shift=1000 --output_dir=Results/ --job_id=mtmcskat_parallel_wrapper_testa1_MAF0.0_geno882_Chr1.traw --ncore=AllCores --max_accuracy=5 --sig_figs=2
Rscript MTMCSKAT_workflow.R --phenodata=poplar_shoot_sample.csv --covariates=poplar_PCs_covariates.csv --raw_file_path=/scratch2/NSF_GWAS/SKAT_SLURMS/inputs/wholeChr/MAF0.0_geno882_Chr2.traw --window_size=3000 --window_shift=1000 --output_dir=Results/ --job_id=mtmcskat_parallel_wrapper_testa1_MAF0.0_geno882_Chr2.traw --ncore=AllCores --max_accuracy=5 --sig_figs=2
Rscript MTMCSKAT_workflow.R --phenodata=poplar_shoot_sample.csv --covariates=poplar_PCs_covariates.csv --raw_file_path=/scratch2/NSF_GWAS/SKAT_SLURMS/inputs/wholeChr/MAF0.0_geno882_Chr3.traw --window_size=3000 --window_shift=1000 --output_dir=Results/ --job_id=mtmcskat_parallel_wrapper_testa1_MAF0.0_geno882_Chr3.traw --ncore=AllCores --max_accuracy=5 --sig_figs=2
Rscript MTMCSKAT_workflow.R --phenodata=poplar_shoot_sample.csv --covariates=poplar_PCs_covariates.csv --raw_file_path=/scratch2/NSF_GWAS/SKAT_SLURMS/inputs/wholeChr/MAF0.0_geno882_Chr4.traw --window_size=3000 --window_shift=1000 --output_dir=Results/ --job_id=mtmcskat_parallel_wrapper_testa1_MAF0.0_geno882_Chr4.traw --ncore=AllCores --max_accuracy=5 --sig_figs=2
Rscript MTMCSKAT_workflow.R --phenodata=poplar_shoot_sample.csv --covariates=poplar_PCs_covariates.csv --raw_file_path=/scratch2/NSF_GWAS/SKAT_SLURMS/inputs/wholeChr/MAF0.0_geno882_Chr5.traw --window_size=3000 --window_shift=1000 --output_dir=Results/ --job_id=mtmcskat_parallel_wrapper_testa1_MAF0.0_geno882_Chr5.traw --ncore=AllCores --max_accuracy=5 --sig_figs=2
Rscript MTMCSKAT_workflow.R --phenodata=poplar_shoot_sample.csv --covariates=poplar_PCs_covariates.csv --raw_file_path=/scratch2/NSF_GWAS/SKAT_SLURMS/inputs/wholeChr/MAF0.0_geno882_Chr6.traw --window_size=3000 --window_shift=1000 --output_dir=Results/ --job_id=mtmcskat_parallel_wrapper_testa1_MAF0.0_geno882_Chr6.traw --ncore=AllCores --max_accuracy=5 --sig_figs=2
Rscript MTMCSKAT_workflow.R --phenodata=poplar_shoot_sample.csv --covariates=poplar_PCs_covariates.csv --raw_file_path=/scratch2/NSF_GWAS/SKAT_SLURMS/inputs/wholeChr/MAF0.0_geno882_Chr7.traw --window_size=3000 --window_shift=1000 --output_dir=Results/ --job_id=mtmcskat_parallel_wrapper_testa1_MAF0.0_geno882_Chr7.traw --ncore=AllCores --max_accuracy=5 --sig_figs=2
Rscript MTMCSKAT_workflow.R --phenodata=poplar_shoot_sample.csv --covariates=poplar_PCs_covariates.csv --raw_file_path=/scratch2/NSF_GWAS/SKAT_SLURMS/inputs/wholeChr/MAF0.0_geno882_Chr8.traw --window_size=3000 --window_shift=1000 --output_dir=Results/ --job_id=mtmcskat_parallel_wrapper_testa1_MAF0.0_geno882_Chr8.traw --ncore=AllCores --max_accuracy=5 --sig_figs=2
Rscript MTMCSKAT_workflow.R --phenodata=poplar_shoot_sample.csv --covariates=poplar_PCs_covariates.csv --raw_file_path=/scratch2/NSF_GWAS/SKAT_SLURMS/inputs/wholeChr/MAF0.0_geno882_Chr9.traw --window_size=3000 --window_shift=1000 --output_dir=Results/ --job_id=mtmcskat_parallel_wrapper_testa1_MAF0.0_geno882_Chr9.traw --ncore=AllCores --max_accuracy=5 --sig_figs=2
